SELECT * FROM (
SELECT 
  AC.ACID_CD_ACIDENTE CODIGO,
  (SELECT ORGA_NM_ORGAO FROM ORGAO WHERE ORGA_SQ_ORGAO = FN_OBTEM_ORGAO_SUPERIOR(AC.ORGA_SQ_ORGAO,8)) NIVEL_1,
  (SELECT ORGA_NM_ORGAO FROM ORGAO WHERE ORGA_SQ_ORGAO = FN_OBTEM_ORGAO_SUPERIOR(Ac.ORGA_SQ_ORGAO,5)) NIVEL_2,
  (SELECT ORGA_NM_ORGAO FROM ORGAO WHERE ORGA_SQ_ORGAO = FN_OBTEM_ORGAO_SUPERIOR(AC.ORGA_SQ_ORGAO,6)) NIVEL_3,
  NULL NIVEL_4,
  O.ORGA_DT_VERSAO_INICIAL VIGENCIA_INICIAL,
  O.ORGA_DT_VERSAO_FINAL VIGENCIA_FINAL,
  AC.ACID_TX_DESCRICAO DESCRICAO,
  AC.ACID_NM_ACIDENTE EVENTO,
  AC.ACID_DT_ACIDENTE DATA_ACIDENTE,
  AC.ACID_HR_ACIDENTE HORA_ACIDENTE,
  (SELECT COUNT(*) FROM ACIDENTADO ACC WHERE ACC.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE) QTDE_ACIDENTADOS,
  -- ACIDENTADO
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Código Acidentado' VALUE ACDT.ACDO_CD_ACIDENTADO,
       	  'Nome Acidentado' VALUE   ACDT.ACDO_NM_ACIDENTADO,
       	  'Tipo de Força de Trabalho' VALUE TFT.TIFT_NM_FORCA,
       	  'Tipo de Lesão' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM ACIDENTADO ACDT
   		 LEFT JOIN TIPO_LESAO TL ON (TL.TILE_CD_TIPO_LESAO = ACDT.TILE_CD_TIPO_LESAO)
   		 LEFT JOIN TEXTO T ON (T.TEXT_CD_TEXTO = TL.TEXT_CD_TEXTO)
   		 LEFT JOIN TEXTO_TRADUZIDO TT ON (TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO),
   	     TIPO_FORCA_TRABALHO TFT
   WHERE ACDT.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND TFT.TIFT_CD_FORCA = ACDT.TIFT_CD_FORCA
   GROUP BY ACDT.ACID_CD_ACIDENTE
   ) AS ACIDENTADO,
  AC.ACID_VL_ESTIMATIVA_CUSTO ESTIMATIVA_CUSTO,
  -- ORGÃO E SUAS VIGÊNCIAS
  -- TIPO DE OCORRÊNCIA
  TOC.TIOC_CD_TIPO_OCORRENCIA CODIGO_TIPO_OCORRENCIA,
  (SELECT DISTINCT TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = TOC.TEXT_CD_TEXTO) TPO_OCORRRENCIA,
  -- CAUSA IMEDIATA
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT	
       (	
       	  'Causa Imediata' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM CAUSA_IMEDIATA CI,
   		 ACIDENTE_CAUSA_IMEDIATA ACI,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND CI.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND ACI.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND ACI.CAIM_CD_CAUSA_IMEDIATA = CI.CAIM_CD_CAUSA_IMEDIATA
   GROUP BY ACI.ACID_CD_ACIDENTE
   ) AS CAUSA_IMEDIATA,
  -- CAUSA BÁSICA
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Causa Básica' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM CAUSA_BASICA CB,
   		 ACIDENTE_CAUSA_BASICA ACB,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND CB.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND ACB.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND ACB.CABA_CD_CAUSA_BASICA = CB.CABA_CD_CAUSA_BASICA
   GROUP BY ACB.ACID_CD_ACIDENTE
   ) AS CAUSA_BASICA,
  -- CLASSE DO ACIDENTE
  AC.ACID_NR_CLASSE CLASSE_ACIDENTE,
  -- AGENTE DE ACIDENTE
  AA.AGAC_CD_AGENTE_ACIDENTE CODIGO_AGENTE_ACIDENTE,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = AA.TEXT_CD_TEXTO) AGENTE_ACIDENTE,
  IM.IMOV_CD_IMOVEL CODIGO_IMOVEL,
  IM.IMOV_NM_IMOVEL NOME_IMOVEL,
  P.PAIS_CD_CODIGO CODIGOPAS,
  P.PAIS_NM_PAIS PAIS,
  AC.ACID_TX_ACAO_IMEDIATA ACAO_IMEDIATA,
  AC.ACID_TX_ACAO_CORRETIVA ACAO_CORRETIVA,
  -- REGRA DE OURO
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Regra de Ouro' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM REGRA_OURO RO,
   	     ACIDENTE_REGRA_OURO ARO,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE ARO.REOU_CD_REGRA_OURO = RO.REOU_CD_REGRA_OURO
     AND AC.ACID_CD_ACIDENTE = ARO.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND RO.TEXT_CD_TEXTO_NOME = T.TEXT_CD_TEXTO
   GROUP BY ARO.ACID_CD_ACIDENTE
   ) AS REGRA_OURO,  
  -- DENOMINAÇÃO DO ACIDNTE
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Denominação do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM DENOMINACAO D,
   	     ACIDENTE_DENOMINACAO AD,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE AD.DENO_CD_DENOMINACAO = D.DENO_CD_DENOMINACAO
     AND AC.ACID_CD_ACIDENTE = AD.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND D.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
   GROUP BY AD.ACID_CD_ACIDENTE
   ) AS DENOMICAO_ACIDENTE,
  -- SUB-DENOMINAÇÃO DO ACIDNTE
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Denominação do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM DENOMINACAO D,
   	     ACIDENTE_DENOMINACAO AD,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE AD.DENO_CD_DENOMINACAO = D.DENO_CD_DENOMINACAO
     AND AC.ACID_CD_ACIDENTE = AD.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND D.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
   GROUP BY AD.ACID_CD_ACIDENTE
   ) AS SUB_DENOMICAO_ACIDENTE,
  AI.ATIN_CD_ATO_INSEGURO CODGIO_ATO_INSEGURO,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = AI.TEXT_CD_TEXTO) ATO_INSEGURO,
   --LOCAL DO ACIDENTE
  LOCA.LOCA_CD_LOCAL CODIGO_LOCAL,
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Local do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM LOCAL L,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND L.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND L.LOCA_CD_LOCAL = AC.LOCA_CD_LOCAL
   GROUP BY L.LOCA_CD_LOCAL
   ) AS LOCAL_ACIDENTE,
  E.ESTA_NM_NOME ESTADO,
  TA.TIPA_CD_TIPOLOGIA_ACIDENTE CODIGO_TIPOLOGIA_ACIDENTE,
  TT.TETR_TX_TEXTO_TRADUZIDO TIPLOGIA_ACIDENTE,
  -- TIPO AIDENTE DE TRÂNSITO
   (
    SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Tipo Acidente de Trânsito' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM TIPO_ACIDENTE_TRANSITO TAT,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND TAT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND AC.TIAT_CD_TIPO_ACIDENTE = TAT.TIAT_CD_TIPO_ACIDENTE
   GROUP BY TAT.TIAT_CD_TIPO_ACIDENTE
   ) AS TIPO_ACIDENTE_TRANSITO,
  COAM.COAM_CD_CONDICAO_AMBIENTE CODIGO_CONDICO_AMBIENTE,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = COAM.TEXT_CD_TEXTO) CONDICAO_AMBIENTE,
  AC.ACID_CD_CHAVE_INCLUSAO CRIADO_POR,
  AC.ACID_DT_INCLUSAO DATA_CRIACAO,
  AC.ACID_CD_CHAVE_ALTERACAO ALTERADO_POR,
  AC.ACID_DT_ALTERACAO DATA_ALTERACAO,
  -- ARQUIVOS ANXADOS
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Arquivos Anexados' VALUE ANEXO.ACAN_NM_ARQUIVO
       )
       returning CLOB
    )      	
   	FROM ACIDENTE_ANEXO ANEXO
   WHERE ANEXO.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE   
   GROUP BY ANEXO.ACID_CD_ACIDENTE
   ) AS ARQUIVOS
FROM ACIDENTE AC
  LEFT JOIN TIPOLOGIA_ACIDENTE TA ON (TA.TIPA_CD_TIPOLOGIA_ACIDENTE = AC.TIPA_CD_TIPOLOGIA_ACIDENTE)
  LEFT JOIN TEXTO T ON (T.TEXT_CD_TEXTO = TA.TEXT_CD_TEXTO)
  LEFT JOIN TEXTO_TRADUZIDO TT ON (T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO)
  LEFT JOIN ORGAO O ON (O.ORGA_SQ_ORGAO = AC.ORGA_SQ_ORGAO)
  LEFT JOIN PAIS P ON (P.PAIS_CD_CODIGO = AC.PAIS_CD_CODIGO)
  LEFT JOIN ESTADO E ON(E.ESTA_CD_CODIGO = AC.ESTA_CD_CODIGO)
  LEFT JOIN TIPO_OCORRENCIA TOC ON (TOC.TIOC_CD_TIPO_OCORRENCIA = AC.TIOC_CD_TIPO_OCORRENCIA)
  LEFT JOIN AGENTE_ACIDENTE AA ON (AA.AGAC_CD_AGENTE_ACIDENTE = AC.AGAC_CD_AGENTE_ACIDENTE)
  LEFT JOIN IMOVEL IM ON (IM.IMOV_CD_IMOVEL = AC.IMOV_CD_IMOVEL)
  LEFT JOIN ATO_INSEGURO AI ON (AI.ATIN_CD_ATO_INSEGURO = AC.ATIN_CD_ATO_INSEGURO)
  LEFT JOIN LOCAL LOCA ON (LOCA.LOCA_CD_LOCAL = AC.LOCA_CD_LOCAL)
   -- TIPO DE ACIDENTE DE TRÂNSITO
  LEFT JOIN TIPO_ACIDENTE_TRANSITO TAT ON (TAT.TIAT_CD_TIPO_ACIDENTE = AC.TIAT_CD_TIPO_ACIDENTE)
  LEFT JOIN CONDICAO_AMBIENTE COAM ON (COAM.COAM_CD_CONDICAO_AMBIENTE = AC.COAM_CD_CONDICAO_AMBIENTE)
  LEFT JOIN (
    SELECT
        ORGA_SQ_ORGAO,
        SYS_CONNECT_BY_PATH(ORGA_NM_ORGAO, ' > ') AS caminho
    FROM
        ORGAO
    START WITH ORGA_SQ_ORGAO_SUPERIOR IS NULL
    CONNECT BY PRIOR ORGA_SQ_ORGAO = ORGA_SQ_ORGAO_SUPERIOR
  ) H ON H.ORGA_SQ_ORGAO = AC.ORGA_SQ_ORGAO
  WHERE AC.ACID_DT_ACIDENTE <= TO_DATE('31/12/2019', 'DD/MM/YYYY')
    --AND AC.ACID_CD_ACIDENTE = 228577
UNION ALL
SELECT 
  AC.ACID_CD_ACIDENTE CODIGO,
  REGEXP_SUBSTR(H.caminho, '[^>]+', 1, 2) AS NIVEL_1,
  REGEXP_SUBSTR(H.caminho, '[^>]+', 1, 3) AS NIVEL_2,
  REGEXP_SUBSTR(H.caminho, '[^>]+', 1, 4) AS NIVEL_3,
  (SELECT ORGA_NM_ORGAO FROM ORGAO WHERE ORGA_SQ_ORGAO = AC.ORGA_SQ_ORGAO) NIVEL_4,
  O.ORGA_DT_VERSAO_INICIAL VIGENCIA_INICIAL,
  O.ORGA_DT_VERSAO_FINAL VIGENCIA_FINAL,
  AC.ACID_TX_DESCRICAO DESCRICAO,
  AC.ACID_NM_ACIDENTE EVENTO,
  AC.ACID_DT_ACIDENTE DATA_ACIDENTE,
  AC.ACID_HR_ACIDENTE HORA_ACIDENTE,
  (SELECT COUNT(*) FROM ACIDENTADO ACC WHERE ACC.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE) QTDE_ACIDENTADOS,
  -- ACIDENTADO
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Código Acidentado' VALUE ACDT.ACDO_CD_ACIDENTADO,
       	  'Nome Acidentado' VALUE   ACDT.ACDO_NM_ACIDENTADO,
       	  'Tipo de Força de Trabalho' VALUE TFT.TIFT_NM_FORCA,
       	  'Tipo de Lesão' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM ACIDENTADO ACDT
   		 LEFT JOIN TIPO_LESAO TL ON (TL.TILE_CD_TIPO_LESAO = ACDT.TILE_CD_TIPO_LESAO)
   		 LEFT JOIN TEXTO T ON (T.TEXT_CD_TEXTO = TL.TEXT_CD_TEXTO)
   		 LEFT JOIN TEXTO_TRADUZIDO TT ON (TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO),
   	     TIPO_FORCA_TRABALHO TFT
   WHERE ACDT.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND TFT.TIFT_CD_FORCA = ACDT.TIFT_CD_FORCA
   GROUP BY ACDT.ACID_CD_ACIDENTE
   ) AS ACIDENTADO,
  AC.ACID_VL_ESTIMATIVA_CUSTO ESTIMATIVA_CUSTO,
  -- ORGÃO E SUAS VIGÊNCIAS
  -- TIPO DE OCORRÊNCIA
  TOC.TIOC_CD_TIPO_OCORRENCIA CODIGO_TIPO_OCORRENCIA,
  (SELECT DISTINCT TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = TOC.TEXT_CD_TEXTO) TPO_OCORRRENCIA,
  -- CAUSA IMEDIATA
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT	
       (	
       	  'Causa Imediata' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM CAUSA_IMEDIATA CI,
   		 ACIDENTE_CAUSA_IMEDIATA ACI,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND CI.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND ACI.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND ACI.CAIM_CD_CAUSA_IMEDIATA = CI.CAIM_CD_CAUSA_IMEDIATA
   GROUP BY ACI.ACID_CD_ACIDENTE
   ) AS CAUSA_IMEDIATA,
  -- CAUSA BÁSICA
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Causa Básica' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM CAUSA_BASICA CB,
   		 ACIDENTE_CAUSA_BASICA ACB,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND CB.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND ACB.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE
     AND ACB.CABA_CD_CAUSA_BASICA = CB.CABA_CD_CAUSA_BASICA
   GROUP BY ACB.ACID_CD_ACIDENTE
   ) AS CAUSA_BASICA,
  -- CLASSE DO ACIDENTE
  AC.ACID_NR_CLASSE CLASSE_ACIDENTE,
  -- AGENTE DE ACIDENTE
  AA.AGAC_CD_AGENTE_ACIDENTE CODIGO_AGENTE_ACIDENTE,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = AA.TEXT_CD_TEXTO) AGENTE_ACIDENTE,
  IM.IMOV_CD_IMOVEL CODIGO_IMOVEL,
  IM.IMOV_NM_IMOVEL NOME_IMOVEL,
  P.PAIS_CD_CODIGO CODIGOPAS,
  P.PAIS_NM_PAIS PAIS,
  AC.ACID_TX_ACAO_IMEDIATA ACAO_IMEDIATA,
  AC.ACID_TX_ACAO_CORRETIVA ACAO_CORRETIVA,
  -- REGRA DE OURO
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Regra de Ouro' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM REGRA_OURO RO,
   	     ACIDENTE_REGRA_OURO ARO,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE ARO.REOU_CD_REGRA_OURO = RO.REOU_CD_REGRA_OURO
     AND AC.ACID_CD_ACIDENTE = ARO.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND RO.TEXT_CD_TEXTO_NOME = T.TEXT_CD_TEXTO
   GROUP BY ARO.ACID_CD_ACIDENTE
   ) AS REGRA_OURO,  
  -- DENOMINAÇÃO DO ACIDNTE
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Denominação do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM DENOMINACAO D,
   	     ACIDENTE_DENOMINACAO AD,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE AD.DENO_CD_DENOMINACAO = D.DENO_CD_DENOMINACAO
     AND AC.ACID_CD_ACIDENTE = AD.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND D.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
   GROUP BY AD.ACID_CD_ACIDENTE
   ) AS DENOMICAO_ACIDENTE,
  -- SUB-DENOMINAÇÃO DO ACIDNTE
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Denominação do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM DENOMINACAO D,
   	     ACIDENTE_DENOMINACAO AD,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE AD.DENO_CD_DENOMINACAO = D.DENO_CD_DENOMINACAO
     AND AC.ACID_CD_ACIDENTE = AD.ACID_CD_ACIDENTE
     AND T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO
     AND D.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
   GROUP BY AD.ACID_CD_ACIDENTE
   ) AS SUB_DENOMICAO_ACIDENTE,
  AI.ATIN_CD_ATO_INSEGURO CODGIO_ATO_INSEGURO,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = AI.TEXT_CD_TEXTO) ATO_INSEGURO,
   --LOCAL DO ACIDENTE
  LOCA.LOCA_CD_LOCAL CODIGO_LOCAL,
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Local do Acidente' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM LOCAL L,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND L.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND L.LOCA_CD_LOCAL = AC.LOCA_CD_LOCAL
   GROUP BY L.LOCA_CD_LOCAL
   ) AS LOCAL_ACIDENTE,
  E.ESTA_NM_NOME ESTADO,
  TA.TIPA_CD_TIPOLOGIA_ACIDENTE CODIGO_TIPOLOGIA_ACIDENTE,
  TT.TETR_TX_TEXTO_TRADUZIDO TIPLOGIA_ACIDENTE,
  -- TIPO AIDENTE DE TRÂNSITO
   (
    SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Tipo Acidente de Trânsito' VALUE TT.TETR_TX_TEXTO_TRADUZIDO
       )
       returning CLOB
    )      	
   	FROM TIPO_ACIDENTE_TRANSITO TAT,
   	     TEXTO T,
   	     TEXTO_TRADUZIDO TT
   WHERE TT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND TAT.TEXT_CD_TEXTO = T.TEXT_CD_TEXTO
     AND AC.TIAT_CD_TIPO_ACIDENTE = TAT.TIAT_CD_TIPO_ACIDENTE
   GROUP BY TAT.TIAT_CD_TIPO_ACIDENTE
   ) AS TIPO_ACIDENTE_TRANSITO,
  COAM.COAM_CD_CONDICAO_AMBIENTE CODIGO_CONDICO_AMBIENTE,
  (SELECT DISTINCT  TT.TETR_TX_TEXTO_TRADUZIDO FROM TEXTO_TRADUZIDO TT, TEXTO T WHERE T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO AND T.TEXT_CD_TEXTO = COAM.TEXT_CD_TEXTO) CONDICAO_AMBIENTE,
  AC.ACID_CD_CHAVE_INCLUSAO CRIADO_POR,
  AC.ACID_DT_INCLUSAO DATA_CRIACAO,
  AC.ACID_CD_CHAVE_ALTERACAO ALTERADO_POR,
  AC.ACID_DT_ALTERACAO DATA_ALTERACAO,
  -- ARQUIVOS ANXADOS
  (
  	SELECT 
  	JSON_ARRAYAGG  	
    (  		
       JSON_OBJECT
       		
       (	
       	  'Arquivos Anexados' VALUE ANEXO.ACAN_NM_ARQUIVO
       )
       returning CLOB
    )      	
   	FROM ACIDENTE_ANEXO ANEXO
   WHERE ANEXO.ACID_CD_ACIDENTE = AC.ACID_CD_ACIDENTE   
   GROUP BY ANEXO.ACID_CD_ACIDENTE
   ) AS ARQUIVOS
FROM ACIDENTE AC
  LEFT JOIN TIPOLOGIA_ACIDENTE TA ON (TA.TIPA_CD_TIPOLOGIA_ACIDENTE = AC.TIPA_CD_TIPOLOGIA_ACIDENTE)
  LEFT JOIN TEXTO T ON (T.TEXT_CD_TEXTO = TA.TEXT_CD_TEXTO)
  LEFT JOIN TEXTO_TRADUZIDO TT ON (T.TEXT_CD_TEXTO = TT.TEXT_CD_TEXTO)
  LEFT JOIN ORGAO O ON (O.ORGA_SQ_ORGAO = AC.ORGA_SQ_ORGAO)
  LEFT JOIN PAIS P ON (P.PAIS_CD_CODIGO = AC.PAIS_CD_CODIGO)
  LEFT JOIN ESTADO E ON(E.ESTA_CD_CODIGO = AC.ESTA_CD_CODIGO)
  LEFT JOIN TIPO_OCORRENCIA TOC ON (TOC.TIOC_CD_TIPO_OCORRENCIA = AC.TIOC_CD_TIPO_OCORRENCIA)
  LEFT JOIN AGENTE_ACIDENTE AA ON (AA.AGAC_CD_AGENTE_ACIDENTE = AC.AGAC_CD_AGENTE_ACIDENTE)
  LEFT JOIN IMOVEL IM ON (IM.IMOV_CD_IMOVEL = AC.IMOV_CD_IMOVEL)
  LEFT JOIN ATO_INSEGURO AI ON (AI.ATIN_CD_ATO_INSEGURO = AC.ATIN_CD_ATO_INSEGURO)
  LEFT JOIN LOCAL LOCA ON (LOCA.LOCA_CD_LOCAL = AC.LOCA_CD_LOCAL)
   -- TIPO DE ACIDENTE DE TRÂNSITO
  LEFT JOIN TIPO_ACIDENTE_TRANSITO TAT ON (TAT.TIAT_CD_TIPO_ACIDENTE = AC.TIAT_CD_TIPO_ACIDENTE)
  LEFT JOIN CONDICAO_AMBIENTE COAM ON (COAM.COAM_CD_CONDICAO_AMBIENTE = AC.COAM_CD_CONDICAO_AMBIENTE)
  LEFT JOIN (
    SELECT
        ORGA_SQ_ORGAO,
        SYS_CONNECT_BY_PATH(ORGA_NM_ORGAO, ' > ') AS caminho
    FROM
        ORGAO
    START WITH ORGA_SQ_ORGAO_SUPERIOR IS NULL
    CONNECT BY PRIOR ORGA_SQ_ORGAO = ORGA_SQ_ORGAO_SUPERIOR
  ) H ON H.ORGA_SQ_ORGAO = AC.ORGA_SQ_ORGAO
  WHERE AC.ACID_DT_ACIDENTE > TO_DATE('31/12/2019', 'DD/MM/YYYY')) ACIDENTE  
  WHERE ACIDENTE.CODIGO = 49072